r"""Extract windows_security_walkthrough_guide_v9.docx to Markdown in ProjectDocs\.

WHY
---
Measured 2026-08-13, a controlled result with one document in two formats:

    ProjectDocs/GatewayGuard_MarketResearch.docx   tracked, in scope, NEVER surfaces for Cloud
    ProjectDocs/GatewayGuard_MarketResearch.md     tracked, in scope, surfaces immediately

Same folder, same connector scope, same commit. Only the .md is readable by
Claude Cloud. Across roughly a dozen searches Cloud has not seen a single
.docx source path.

The guide has been committed and pushed since 2026-07-28 -- sixteen days --
and Cloud still cannot read it. So this is NOT the "in the folder, not the
repo" failure. Committing harder does not fix it. Extraction does.

The .docx stays in the repository for safekeeping and version history. This
.md is what anyone actually reads and rewrites from -- the same arrangement
already proved by build_marketing_sourcepack.py.

Generated. Never hand-edit; the next run overwrites.
"""

import html
import re
import subprocess
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# 2026-08-15: the master moved to Masters\, OUT of connector scope. Cloud
# cannot read a .docx anyway, so carrying it in ProjectDocs\ cost connector
# capacity and returned nothing. The extraction this script writes INTO
# ProjectDocs\ is what Cloud reads and rewrites from.
SRC = ROOT / "Masters" / "windows_security_walkthrough_guide_v9.docx"

STAMP = subprocess.run(
    ["powershell", "-NoProfile", "-Command", "Get-Date -Format 'yyyy-MM-dd HH:mm'"],
    capture_output=True, text=True).stdout.strip()
FSTAMP = STAMP.replace(" ", "-").replace(":", "")

# Word style -> markdown heading level
HEADING = {"Heading1": "##", "Heading2": "###", "Heading3": "####",
           "Title": "#", "Heading4": "#####"}


def paragraphs(path):
    """Yield (style, text) for every paragraph, so headings survive."""
    with zipfile.ZipFile(path) as z:
        xml = z.read("word/document.xml").decode("utf-8", "replace")
    for m in re.finditer(r"<w:p[ >].*?</w:p>", xml, re.S):
        blk = m.group(0)
        st = re.search(r'<w:pStyle w:val="([^"]+)"', blk)
        style = st.group(1) if st else ""
        # Table cell boundaries would otherwise fuse words together.
        text = re.sub(r"<w:tab/>", "  ", blk)
        text = html.unescape(re.sub(r"<[^>]+>", "", text))
        yield style, re.sub(r"[ \t]+", " ", text).strip()


def main():
    if not SRC.exists():
        raise SystemExit(f"not found: {SRC}")

    body, headings = [], 0
    for style, text in paragraphs(SRC):
        if not text:
            continue
        h = HEADING.get(style)
        if h:
            headings += 1
            body.append(f"\n{h} {text}\n")
        elif style.startswith("ListParagraph"):
            body.append(f"- {text}")
        else:
            body.append(text)

    full = "\n".join(body)
    words = len(re.findall(r"\b\w+\b", full))

    def n(pat):
        return len(re.findall(pat, full, re.I))

    head = f"""<!-- Dated: {STAMP} ET -->
<!-- Editor: Claude Code (CGDELL) -->
<!-- GENERATED by Tool/build_guide_sourcepack.py -- do not hand-edit. -->
# Windows Security Walkthrough Guide v9 -- readable text

- **Document Name:** GatewayGuard_GuideV9-SourcePack
- **Last Modified:** {STAMP} ET
- **Source of record:** `Masters/windows_security_walkthrough_guide_v9.docx`
- **Status:** GENERATED extraction. The `.docx` remains the master.

---

## WHY THIS FILE EXISTS

**measured 2026-08-13, a controlled result:** `GatewayGuard_MarketResearch.docx`
and `GatewayGuard_MarketResearch.md` are both tracked, both in `ProjectDocs/`,
both in connector scope. **Claude Cloud reads the `.md` and has never once
surfaced the `.docx`** -- across roughly a dozen searches it has not seen a
single `.docx` source path.

The guide has been committed and pushed **since 2026-07-28, sixteen days**.
Cloud still cannot read it. So this is not the "file is in the folder, not the
repo" failure that explains the untracked guide PDFs. Committing harder does
not help. **Extraction does.**

Git accepts `.docx` perfectly well -- it stores it, versions it, and can
recover it. What it cannot do is *diff* it: two versions differ by one opaque
line. This project runs on reviewable change, so the `.docx` is kept for
safekeeping and this `.md` is what gets read and rewritten from.

*Anthropic's connector documentation does not state which file types are
indexed. Treat "`.docx` is not indexed" as **inferred**, not settled.*

## WHAT IS WRONG WITH THE GUIDE -- measured, before anyone rewrites it

- **A SHIPPING DEFECT ON PAGE 1.** The exported PDF's table of contents was
  never updated. The paid product opens with
  *'Right-click here and choose "Update Field" to populate the Table of
  Contents.'* Present **{n('Update Field')} times** in the source.
- **"GatewayGuard" appears {n('GatewayGuard')} times. "Checkup" appears
  {n('Checkup')} times.** No cover, no author, no copyright notice -- in a
  product that sells for $19.99 and whose copyright registration is an open
  task.
- **Three PL-4 breaches:** *"the single biggest factor in PC security"*,
  *"the most powerful built-in tool"*, *"biggest single reduction in malware
  blast radius"*.
- **"whether" x{n(r"\bwhether\b")}** (banned, PL-1). "whereas"
  x{n(r"\bwhereas\b")}. "switch" as a verb for a setting: none found.
- **"open-source" x{n(r"open[- ]source")}** -- the Chromium glossary entry.
  **Legitimate. Do not sweep it.**
- **Coverage gap.** The free website covers **19 settings**; this guide covers
  roughly **12**. Absent entirely: **Periodic scanning, Fast Startup, Wake on
  LAN**. Remote Desktop, Advertising ID and Diagnostic data share one table row.

## THE AUDIENCE DECISION -- Bill, 2026-08-13

**The guide's reader is the non-technical senior on their own PC, not the
family helper.** Filed under WRITING AUDIENCE DEFAULT.

This is why the pronouns matter: the text uses **"the user"
{n(r"\bthe user\b")} times**, and one line tells the reader to *"ask the user
first"*. **A senior sitting alone has nobody to ask.** The helper voice quietly
assumes a second competent person in the room, and removing that person removes
the safety net at the riskiest moment. Every such construction has to go.

---

## EXTRACTION

{len(body):,} blocks · {headings} headings · {words:,} words · source
{SRC.stat().st_size:,} bytes

---

"""

    out = ROOT / "ProjectDocs" / f"GatewayGuard_GuideV9-SourcePack-{FSTAMP}.md"
    out.write_text(head + full + "\n", encoding="utf-8", newline="")
    print(f"wrote {out.name}  ({out.stat().st_size:,} bytes, "
          f"{len(body):,} blocks, {headings} headings, {words:,} words)")


if __name__ == "__main__":
    main()
