# Dated: 2026-08-20 12:10 ET
# File: Check-Docs-2026-08-20.ps1
#
#   WHY THIS EXISTS: this project has two dozen mechanical gates for code and
#   none for documents, and documents are where the drift lives. Its own
#   playbook says it -- A GATE WITH NO CHECK IS A WISH. Named in SyncPlan
#   section 6c on 2026-08-09 and unbuilt for eleven days, during which the
#   briefing sat three builds stale on its own first line.
#
#   THE FIVE CHECKS ARE 6c's, IN 6c's ORDER:
#     1. No two documents state the same volatile fact -- and the live ones
#        are checked against the machine, not only against each other
#     2. Every dated filename named as a pointer actually exists
#     3. Every document's internal "Dated:" matches the date in its filename
#     4. Only one live copy of each document family, or CURRENT.md names it
#     5. The stamp line matches the file's own content hash
#
#   THE GOVERNING SET IS READ OUT OF ProjectDocs\CURRENT.md, NEVER TYPED HERE.
#   CURRENT.md is generated by Update-Current.ps1 and refuses to write a
#   pointer with a hole in it. A checker carrying its own hand-kept filename
#   list would be the exact failure it exists to catch, wearing a lab coat.
#
#   ROLLOUT IS THE GATE 12b RATCHET. Checks 2, 3 and 4 already have known
#   exceptions, so they carry a baseline COUNT and report rather than fail.
#   Going ABOVE a baseline fails the run -- something new appeared. Going
#   below prints the lower number to write back in. The list is only ever
#   allowed to get shorter.
#
#   READ-ONLY. It changes nothing, deletes nothing, needs no administrator.

$ErrorActionPreference = "Continue"

$repo = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $repo

$docs = Join-Path $repo "ProjectDocs"

$stamp   = Get-Date -Format "yyyy-MM-dd_HH-mm"
$results = Join-Path $repo "Test_Results"
if (-not (Test-Path $results)) { New-Item -ItemType Directory -Path $results -Force | Out-Null }
$outFile = Join-Path $results ("DocCheck-" + $env:COMPUTERNAME + "-" + $stamp + ".txt")

$L = New-Object System.Collections.ArrayList
function W([string]$t) { [void]$L.Add($t); Write-Host $t }

$problems = 0

# ------------------------------------------------------------ THE RATCHET
# Each number is what THIS SCRIPT measured on 2026-08-20 on CGDELL -- not an
# estimate, and not a figure carried over from some other method. LOWER THEM
# as the lists shrink. Never raise one to make a run go green; that is the one
# edit that turns this file back into a wish.
#
#   The 10 dead pointers in the live documents, by name:
#     briefing:528            -> GatewayGuard-Log-2026-08-19_21-08.txt
#                                (real, and the evidence for the top ascii43
#                                 finding -- it is still on SANDY, uncollected)
#     ProjectInstructions x7  -> GatewayGuide_Project_Instructions-2026-07-03
#                                TestHistory-ascii39-...-0914 (three times)
#                                CodingStandards-2026-07-20-0908
#                                CPM_Schedule-2026-07-30-2208
#                                ProjectInstructions-2026-08-02-1820
#     CodingStandards:102     -> CodingStandards-2026-07-21-1009
#   The 1 date mismatch:
#     TestHistory-ascii39-2026-08-02-1335.md, header says 2026-08-02 11:16
#   The 4 families with no anchor:
#     GuideRewrite-Draft (3), License-TEXT (3), MarketingPlan (2),
#     Profile_Instructions_Universal (2)
$BASE_DEAD_POINTERS_GOVERNING = 10
$BASE_DEAD_POINTERS_ALL       = 52
$BASE_DATE_MISMATCH           = 1
$BASE_UNRESOLVED_FAMILIES     = 4

$bt = [char]96   # backtick, built by code point so the regex below stays legible

W ("=" * 70)
W "  DOCUMENT GATE  --  SyncPlan section 6c"
W ("=" * 70)
W ("  repository : " + $repo)
W ("  machine    : " + $env:COMPUTERNAME)
W ("  run at     : " + (Get-Date -Format "yyyy-MM-dd HH:mm:ss"))
W ""

# ====================================================================
#  Read the governing set out of CURRENT.md
# ====================================================================
$currentMd = Join-Path $docs "CURRENT.md"
if (-not (Test-Path -LiteralPath $currentMd)) {
    W "  STOP: ProjectDocs\CURRENT.md is missing. Run Tool\Run-UpdateCurrent.bat."
    W "  Every check below reads the live filenames out of it."
    Set-Content -LiteralPath $outFile -Value ($L -join "`r`n") -Encoding UTF8
    exit 1
}

# Rows look like:  | Briefing -- read this first | `_READ-FIRST-...md` | 0 |
$rowPat = '^\|\s*(.+?)\s*\|\s*' + $bt + '(.+?)' + $bt + '\s*\|\s*(\d+)\s*\|'
$namedCurrent = @{}      # label -> filename
$namedOlder   = @{}      # label -> count of older versions CURRENT.md admits to
foreach ($line in (Get-Content -LiteralPath $currentMd -Encoding UTF8)) {
    $m = [regex]::Match($line, $rowPat)
    if ($m.Success -and $m.Groups[1].Value -ne "What it is") {
        $namedCurrent[$m.Groups[1].Value] = $m.Groups[2].Value
        $namedOlder[$m.Groups[1].Value]   = [int]$m.Groups[3].Value
    }
}

# The documents that speak in the PRESENT TENSE about NOW. A dated record --
# a session log, a test history, a field plan -- is allowed to carry an old
# figure, because it is reporting what was true on its own date.
$factLabels = @("Briefing -- read this first", "Project instructions",
                "Coding standards", "Defect prevention playbook",
                "Website standards")
$factFiles = New-Object System.Collections.ArrayList
foreach ($lab in $factLabels) {
    if ($namedCurrent.ContainsKey($lab)) {
        $p = Join-Path $docs $namedCurrent[$lab]
        if (Test-Path -LiteralPath $p) { [void]$factFiles.Add($p) }
    }
}
$claudeMd = Join-Path $repo "CLAUDE.md"
if (Test-Path -LiteralPath $claudeMd) { [void]$factFiles.Add($claudeMd) }

W ("  governing documents named by CURRENT.md : " + $namedCurrent.Count)
W ("  of those, present-tense about NOW       : " + $factFiles.Count + " (incl. CLAUDE.md)")
W ""

# ====================================================================
#  1. NO TWO DOCUMENTS STATE THE SAME VOLATILE FACT
# ====================================================================
W "-- 1. VOLATILE FACTS -- STATED ONCE, AND TRUE ------------------------"
W "  Section 7b: a fact stated once can be wrong. A fact stated twice can be"
W "  INCONSISTENT, and then nobody knows which to believe. So each fact below"
W "  is counted across the live documents AND checked against the machine."
W ""

# A sentence that QUOTES a wrong old figure in order to correct it is not a
# competing claim -- it is the record of the correction. The briefing's own
# change history opens with *said "Active build: ascii39"*, and counting that
# as a live claim would make this gate report the very fix that closed it.
$notAClaim = '\bsaid\b|[Ss]upersede|[Ss]uperseded|used to|formerly|it had|stale|' +
             'was\s+\*?\*?ascii|previously'

function Get-Fact([string]$path, [string]$pattern) {
    # Returns every captured value of $pattern in $path, with its line number.
    $hits = New-Object System.Collections.ArrayList
    $n = 0
    foreach ($line in (Get-Content -LiteralPath $path -Encoding UTF8)) {
        $n++
        if ($line -match $notAClaim) { continue }
        foreach ($m in [regex]::Matches($line, $pattern)) {
            [void]$hits.Add(@{ value = $m.Groups[1].Value; line = $n })
        }
    }
    return $hits
}

# Documents write a figure the way a human reads it -- "8,921", "ascii42".
# The machine returns "8921" and "42". Compare the numbers, not the decoration.
function Get-Normal([string]$v) {
    return ($v -replace ',', '' -replace '(?i)^ascii', '').Trim()
}

function Test-Fact([string]$name, [string]$pattern, [string]$measured, [string]$note) {
    $stated = New-Object System.Collections.ArrayList
    foreach ($f in $factFiles) {
        foreach ($h in (Get-Fact $f $pattern)) {
            [void]$stated.Add(@{ file = (Split-Path $f -Leaf); line = $h.line; value = $h.value })
        }
    }
    W ("  " + $name)
    if ($stated.Count -eq 0) {
        W ("      stated in no live document. measured: " + $measured)
        W ""
        return 0
    }
    $values = @($stated | ForEach-Object { Get-Normal $_.value } | Sort-Object -Unique)
    foreach ($s in $stated) {
        W ("      " + $s.file + ":" + $s.line + "  says " + $s.value)
    }
    W ("      measured now : " + $measured)
    $bad = 0
    if ($values.Count -gt 1) {
        W "      DISAGREE -- the live documents do not tell the same story."
        $bad = 1
    }
    if ($values -notcontains (Get-Normal $measured)) {
        W "      STALE -- what the documents say is not what the machine says."
        W ("      " + $note)
        $bad = 1
    }
    if ($bad -eq 0) { W "      OK -- agrees with itself and with the machine." }
    W ""
    return $bad
}

# --- measure the machine ------------------------------------------------
# VERIFIED 2026-08-20 measured on CGDELL: the newest build on disk is
# Tool\W11-SecurityHardening-v3-ascii42-2026-08-19-1830.ps1, 9,301 total
# lines and 8,921 non-blank, which is what both live documents claim.
$buildFiles = @(Get-ChildItem -LiteralPath (Join-Path $repo "Tool") -Filter "W11-SecurityHardening-v3-ascii*.ps1" -File -ErrorAction SilentlyContinue)
$newestBuild = $null
$newestN = -1
foreach ($b in $buildFiles) {
    $m = [regex]::Match($b.Name, 'ascii(\d+)')
    if ($m.Success -and [int]$m.Groups[1].Value -gt $newestN) {
        $newestN = [int]$m.Groups[1].Value
        $newestBuild = $b
    }
}
$mBuild = "none"
$mTotal = "0"
$mNonBlank = "0"
if ($newestBuild) {
    $mBuild = "ascii" + $newestN
    $blines = [System.IO.File]::ReadAllLines($newestBuild.FullName)
    $mTotal = "" + $blines.Count
    $mNonBlank = "" + (@($blines | Where-Object { $_.Trim() -ne "" })).Count
}

# VERIFIED 2026-08-20 measured on CGDELL: "git rev-list --count HEAD" prints
# a bare integer; "git ls-files" one path per line; "git rev-list --count
# origin/main..HEAD" the number of commits GitHub has not got yet.
$mCommits  = "" + (& git rev-list --count HEAD 2>$null)
$mTracked  = "" + (@(& git ls-files 2>$null)).Count
$mUnpushed = "" + (& git rev-list --count origin/main..HEAD 2>$null)

# EVERY PATTERN BELOW MATCHES A DECLARATION, NEVER A MENTION. The first
# version of this gate matched any "asciiNN" and reported seventeen claims
# about the current build, sixteen of which were ordinary prose about older
# ones -- counting a proxy instead of the thing, which is the failure the
# project instructions name in so many words. "Active build:" and "Current
# build:" are the two forms the live documents actually use; a build number
# in a sentence is history and is left alone.
$problems += Test-Fact "ACTIVE BUILD NUMBER" '(?:Active build|Current build)[^\r\n]{0,8}?ascii(\d+)' $mBuild `
    "Update CLAUDE.md line 9 and briefing section 1 in the same edit as the build."
$problems += Test-Fact "BUILD SIZE -- non-blank lines" '\*?\*?([\d,]{4,7})\*?\*? non-blank' $mNonBlank `
    "Appendix A method: Measure-Object -Line on the non-blank count."
# "lines / N total" is the live form. The Playbook's "non-blank lines (5,900
# total)" is a defect write-up about a file that no longer exists, so the
# slash is what separates a statement of the build's size from a memory of one.
$problems += Test-Fact "BUILD SIZE -- total lines" 'lines\s*/\s*([\d,]{4,7}) total' $mTotal `
    "Appendix A method: total lines including blanks."
$problems += Test-Fact "COMMITS" '\|\s*Commits\s*\|\s*\*?\*?([\d,]+)' $mCommits `
    "Briefing section 1 says these are stated HERE ONLY. Re-measure at session end."
$problems += Test-Fact "TRACKED FILES" '\|\s*Tracked files\s*\|\s*\*?\*?([\d,]+)' $mTracked `
    "Take it three ways -- ls-files, ls-files -z, ls-tree -r HEAD -- and say so."
$problems += Test-Fact "UNPUSHED COMMITS" '\|\s*Unpushed\s*\|\s*\*?\*?([\d,]+)' $mUnpushed `
    "Push, then re-measure. A stale zero here is the worst line in the document."

# ====================================================================
#  2. DEAD POINTERS
# ====================================================================
W "-- 2. DEAD POINTERS --------------------------------------------------"
W "  A pointer that lies is worse than no pointer. Every dated filename in"
W "  backticks must exist somewhere in the tree."
W ""

# Every filename on disk, once.
$onDisk = New-Object 'System.Collections.Generic.HashSet[string]'
foreach ($f in (Get-ChildItem -LiteralPath $repo -Recurse -File -Force -ErrorAction SilentlyContinue)) {
    if ($f.FullName -like "*\.git\*") { continue }
    [void]$onDisk.Add($f.Name)
}

$ptrPat = $bt + '([^' + $bt + ']*\d{4}-\d{2}-\d{2}[^' + $bt + ']*?\.(?:md|ps1|bat|py|txt|docx|pdf|pptx))' + $bt

# A NAME IS NOT ALWAYS A POINTER. 6c says "referenced in a pointer context",
# and it was right to. These three contexts name a file in order to say it is
# GONE, so finding it absent is the sentence working, not failing.
$notPointer = '[Ss]upersede|[Ss]uperseded|[Rr]etired|[Rr]eplaced by|no longer|was renamed|' +
              'Older versions|older version|previous version|[Dd]eleted|[Rr]emoved|used to be'

function Get-DeadPointers([string]$path) {
    $out = New-Object System.Collections.ArrayList
    $n = 0
    foreach ($line in (Get-Content -LiteralPath $path -Encoding UTF8)) {
        $n++
        if ($line -match $notPointer) { continue }
        foreach ($m in [regex]::Matches($line, $ptrPat)) {
            $raw = $m.Groups[1].Value
            # An elided name -- "W11-...ascii33-2026-07-19.ps1" -- is prose, not a path.
            if ($raw -match '\.\.\.' -or $raw -match '\*') { continue }
            $base = Split-Path ($raw -replace '\\', '/') -Leaf
            if (-not $onDisk.Contains($base)) {
                [void]$out.Add(@{ line = $n; name = $base })
            }
        }
    }
    return $out
}

$deadGov = 0
foreach ($f in $factFiles) {
    foreach ($d in (Get-DeadPointers $f)) {
        $deadGov++
        W ("      " + (Split-Path $f -Leaf) + ":" + $d.line + "  -> " + $d.name)
    }
}
W ("  dead pointers in the live documents : " + $deadGov + "   (baseline " + $BASE_DEAD_POINTERS_GOVERNING + ")")

$deadAll = 0
foreach ($f in (Get-ChildItem -LiteralPath $docs -Filter "*.md" -File)) {
    $deadAll += (Get-DeadPointers $f.FullName).Count
}
W ("  dead pointers across all ProjectDocs : " + $deadAll + "   (baseline " + $BASE_DEAD_POINTERS_ALL + ")")

if ($deadGov -gt $BASE_DEAD_POINTERS_GOVERNING -or $deadAll -gt $BASE_DEAD_POINTERS_ALL) {
    $problems++
    W "  RESULT: FAIL -- a NEW dead pointer appeared. Fix it, do not raise the baseline."
} elseif ($deadGov -lt $BASE_DEAD_POINTERS_GOVERNING -or $deadAll -lt $BASE_DEAD_POINTERS_ALL) {
    W ("  RESULT: improved. Lower the baselines in this script to " + $deadGov + " and " + $deadAll + ".")
} else {
    W "  RESULT: holding at the baseline. Carried, not passed."
}
W ""

# ====================================================================
#  3. THE Dated: HEADER MATCHES THE FILENAME
# ====================================================================
W "-- 3. FILENAME DATE vs INTERNAL Dated: -------------------------------"
W "  Naming standard: the two are updated in the same edit, never one alone."
W ""

$mismatch = 0
$noStamp  = 0
foreach ($f in (Get-ChildItem -LiteralPath $docs -Filter "*.md" -File)) {
    # Generated twins carry the GENERATION time, not the source's date. That is
    # correct behaviour for build_readable_twins.py, so they are out of scope.
    if ($f.Name -like "*-TEXT.md") { continue }
    if ($f.Name -eq "CURRENT.md")  { continue }   # generated; carries Generated:, not Dated:

    $fm = [regex]::Match($f.Name, '(\d{4}-\d{2}-\d{2})(?:-(\d{2})(\d{2}))?')
    if (-not $fm.Success) { continue }            # no date in the name, nothing to compare

    $head = (Get-Content -LiteralPath $f.FullName -TotalCount 6 -Encoding UTF8) -join "`n"
    $hm = [regex]::Match($head, 'Dated:\s*(\d{4}-\d{2}-\d{2})(?:\s+(\d{2}):(\d{2}))?')
    if (-not $hm.Success) { $noStamp++; continue }

    $bad = $false
    if ($hm.Groups[1].Value -ne $fm.Groups[1].Value) { $bad = $true }
    if ($fm.Groups[2].Success -and $hm.Groups[2].Success) {
        if ($fm.Groups[2].Value -ne $hm.Groups[2].Value -or $fm.Groups[3].Value -ne $hm.Groups[3].Value) { $bad = $true }
    }
    if ($bad) {
        $mismatch++
        W ("      " + $f.Name + "  header says " + $hm.Groups[0].Value)
    }
}
W ("  documents whose header disagrees with their name : " + $mismatch + "   (baseline " + $BASE_DATE_MISMATCH + ")")
W ("  documents carrying no Dated: header at all       : " + $noStamp + "   (reported, not failed)")
if ($mismatch -gt $BASE_DATE_MISMATCH) {
    $problems++
    W "  RESULT: FAIL -- fix the header, or rename the file. Same edit, both."
} else {
    W "  RESULT: clear."
}
W ""

# ====================================================================
#  4. ONE LIVE COPY OF EACH DOCUMENT FAMILY
# ====================================================================
W "-- 4. ONE LIVE COPY, OR CURRENT.md NAMES WHICH ONE -------------------"
W "  Several copies are fine as long as something says which is live. What is"
W "  not fine is three drafts and nothing to choose between them."
W ""

$fam = @{}
foreach ($f in (Get-ChildItem -LiteralPath $docs -Filter "*.md" -File)) {
    $m = [regex]::Match($f.Name, '^(.*?)-(\d{4}-\d{2}-\d{2}(?:-\d{3,4})?)(.*)$')
    if (-not $m.Success) { continue }
    $key = $m.Groups[1].Value + $m.Groups[3].Value
    if (-not $fam.ContainsKey($key)) { $fam[$key] = New-Object System.Collections.ArrayList }
    [void]$fam[$key].Add($f.Name)
}

$namedFiles = New-Object 'System.Collections.Generic.HashSet[string]'
foreach ($v in $namedCurrent.Values) { [void]$namedFiles.Add((Split-Path ($v -replace '\\','/') -Leaf)) }

$unresolved = 0
foreach ($k in ($fam.Keys | Sort-Object)) {
    if ($fam[$k].Count -lt 2) { continue }
    $isNamed = $false
    foreach ($n in $fam[$k]) { if ($namedFiles.Contains($n)) { $isNamed = $true } }
    if ($isNamed) {
        W ("      OK        " + $k + "  -- " + $fam[$k].Count + " copies, CURRENT.md names the live one")
    } else {
        $unresolved++
        W ("      NO ANCHOR " + $k + "  -- " + $fam[$k].Count + " copies, nothing says which:")
        foreach ($n in ($fam[$k] | Sort-Object)) { W ("                    " + $n) }
    }
}
W ("  families with copies and no anchor : " + $unresolved + "   (baseline " + $BASE_UNRESOLVED_FAMILIES + ")")
if ($unresolved -gt $BASE_UNRESOLVED_FAMILIES) {
    $problems++
    W "  RESULT: FAIL -- add a row to Update-Current.ps1, or retire the old copies."
} elseif ($unresolved -lt $BASE_UNRESOLVED_FAMILIES) {
    W ("  RESULT: improved. Lower the baseline in this script to " + $unresolved + ".")
} else {
    W "  RESULT: holding at the baseline. Carried, not passed."
}
W ""

# ====================================================================
#  5. THE CONTENT STAMP
# ====================================================================
W "-- 5. THE CONTENT STAMP ----------------------------------------------"
W "  SyncPlan 6c, last item: the stamp should carry a hash of the file's own"
W "  content. Without one, two files with the same Dated: line and different"
W "  text read as identical -- which is exactly what a mid-session edit makes."
W "  SyncPlan records the hash as ASPIRATIONAL, not built. This section"
W "  verifies any stamp that IS there and counts the rest. It does not invent"
W "  a number and call it adopted."
W ""

$withHash = 0; $hashOK = 0; $hashBad = 0
foreach ($f in $factFiles) {
    $lines = [System.IO.File]::ReadAllLines($f)
    $hm = $null
    foreach ($ln in ($lines | Select-Object -First 6)) {
        $x = [regex]::Match($ln, 'Content-SHA256:\s*([0-9a-fA-F]{8,64})')
        if ($x.Success) { $hm = $x; break }
    }
    if (-not $hm) { continue }
    $withHash++
    # Hash the file with its own stamp line blanked, so the stamp can describe
    # the file it lives in without chasing its own tail.
    $body = ($lines | Where-Object { $_ -notmatch 'Content-SHA256:' }) -join "`n"
    $sha  = [System.BitConverter]::ToString(
                (New-Object System.Security.Cryptography.SHA256Managed).ComputeHash(
                    [System.Text.Encoding]::UTF8.GetBytes($body))).Replace("-", "").ToLower()
    if ($sha.StartsWith($hm.Groups[1].Value.ToLower())) {
        $hashOK++
        W ("      OK   " + (Split-Path $f -Leaf))
    } else {
        $hashBad++
        $problems++
        W ("      EDITED SINCE STAMPING  " + (Split-Path $f -Leaf))
        W ("           stamp says " + $hm.Groups[1].Value + ", content is " + $sha.Substring(0, 16))
    }
}
W ("  live documents carrying a content hash : " + $withHash + " of " + $factFiles.Count)
if ($withHash -eq 0) {
    W "  RESULT: not adopted yet. This is SyncPlan 6c's open item, unchanged."
    W "          To adopt: add a line to each live document reading"
    W "          Content-SHA256: <first 16 hex of the SHA-256 of the file with"
    W "          that line removed>, and this section starts enforcing it."
} elseif ($hashBad -eq 0) {
    W "  RESULT: every stamp present matches its file."
} else {
    W ("  RESULT: FAIL -- " + $hashBad + " document(s) changed after being stamped.")
}
W ""

# ====================================================================
W ("=" * 70)
if ($problems -eq 0) {
    W "  ALL CLEAR"
} else {
    W ("  " + $problems + " THING(S) NEED ATTENTION -- see above")
}
W ("=" * 70)
W ""
W "  Baselines are a RATCHET. Fix the finding; never raise the number."
W "  Sections 2 and 4 report at their baseline rather than failing, because"
W "  the exceptions predate the gate. Section 1 fails on sight -- it is small,"
W "  it is exact, and it is where the briefing went three builds stale."

Set-Content -LiteralPath $outFile -Value ($L -join "`r`n") -Encoding UTF8
Write-Host ""
Write-Host ("  Saved to: " + $outFile) -ForegroundColor Green
Write-Host ""
